/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjnitest_HeaderFile */

#ifndef _Included_com_example_myjnitest_HeaderFile
#define _Included_com_example_myjnitest_HeaderFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myjnitest_HeaderFile_doVoid
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doShort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doShort
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doArray
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_myjnitest_HeaderFile_doArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: (DFZ[C)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt__DFZ_3C
  (JNIEnv *, jclass, jdouble, jfloat, jboolean, jcharArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: ([I[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt___3I_3D
  (JNIEnv *, jobject, jintArray, jdoubleArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doInt
 * Signature: ([I[D[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjnitest_HeaderFile_doInt___3I_3D_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jintArray, jdoubleArray, jobjectArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myjnitest_HeaderFile_doString__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doObject
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_example_myjnitest_HeaderFile_doObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doString
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_myjnitest_HeaderFile_doString___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_example_myjnitest_HeaderFile
 * Method:    doObjects
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_myjnitest_HeaderFile_doObjects
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
